// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Command {
    #[prost(enumeration = "command::CommandType", tag = "1")]
    pub r#type: i32,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(oneof = "command::Payload", tags = "3, 4, 5, 6, 7")]
    pub payload: ::core::option::Option<command::Payload>,
}
/// Nested message and enum types in `Command`.
pub mod command {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum CommandType {
        UnknownCommand = 0,
        StartCpuRecording = 1,
        StopCpuRecording = 2,
        StartAllocRecording = 3,
        StopAllocRecording = 4,
        SaveSnapshot = 5,
        GetCpuData = 6,
        GetMemoryData = 7,
        GetThreadData = 8,
        SetSamplingInterval = 9,
        SetThreadFilter = 10,
    }
    impl CommandType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::UnknownCommand => "UNKNOWN_COMMAND",
                Self::StartCpuRecording => "START_CPU_RECORDING",
                Self::StopCpuRecording => "STOP_CPU_RECORDING",
                Self::StartAllocRecording => "START_ALLOC_RECORDING",
                Self::StopAllocRecording => "STOP_ALLOC_RECORDING",
                Self::SaveSnapshot => "SAVE_SNAPSHOT",
                Self::GetCpuData => "GET_CPU_DATA",
                Self::GetMemoryData => "GET_MEMORY_DATA",
                Self::GetThreadData => "GET_THREAD_DATA",
                Self::SetSamplingInterval => "SET_SAMPLING_INTERVAL",
                Self::SetThreadFilter => "SET_THREAD_FILTER",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNKNOWN_COMMAND" => Some(Self::UnknownCommand),
                "START_CPU_RECORDING" => Some(Self::StartCpuRecording),
                "STOP_CPU_RECORDING" => Some(Self::StopCpuRecording),
                "START_ALLOC_RECORDING" => Some(Self::StartAllocRecording),
                "STOP_ALLOC_RECORDING" => Some(Self::StopAllocRecording),
                "SAVE_SNAPSHOT" => Some(Self::SaveSnapshot),
                "GET_CPU_DATA" => Some(Self::GetCpuData),
                "GET_MEMORY_DATA" => Some(Self::GetMemoryData),
                "GET_THREAD_DATA" => Some(Self::GetThreadData),
                "SET_SAMPLING_INTERVAL" => Some(Self::SetSamplingInterval),
                "SET_THREAD_FILTER" => Some(Self::SetThreadFilter),
                _ => None,
            }
        }
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "3")]
        StartCpuRecording(super::StartCpuRecordingCommand),
        #[prost(message, tag = "4")]
        SaveSnapshot(super::SaveSnapshotCommand),
        #[prost(message, tag = "5")]
        GetCpuData(super::GetCpuDataCommand),
        #[prost(message, tag = "6")]
        SetSamplingInterval(super::SetSamplingIntervalCommand),
        #[prost(message, tag = "7")]
        SetThreadFilter(super::SetThreadFilterCommand),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartCpuRecordingCommand {
    #[prost(enumeration = "start_cpu_recording_command::CpuMode", tag = "1")]
    pub mode: i32,
    #[prost(uint32, tag = "2")]
    pub sampling_interval_ms: u32,
}
/// Nested message and enum types in `StartCpuRecordingCommand`.
pub mod start_cpu_recording_command {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum CpuMode {
        Sampling = 0,
        Instrumentation = 1,
        AsyncSampling = 2,
    }
    impl CpuMode {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Sampling => "SAMPLING",
                Self::Instrumentation => "INSTRUMENTATION",
                Self::AsyncSampling => "ASYNC_SAMPLING",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "SAMPLING" => Some(Self::Sampling),
                "INSTRUMENTATION" => Some(Self::Instrumentation),
                "ASYNC_SAMPLING" => Some(Self::AsyncSampling),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SaveSnapshotCommand {
    #[prost(string, tag = "1")]
    pub file_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCpuDataCommand {
    #[prost(string, tag = "1")]
    pub thread_filter: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetSamplingIntervalCommand {
    #[prost(uint32, tag = "1")]
    pub interval_ms: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetThreadFilterCommand {
    #[prost(string, tag = "1")]
    pub thread_pattern: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub thread_status: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProfilingData {
    #[prost(enumeration = "profiling_data::DataType", tag = "1")]
    pub r#type: i32,
    #[prost(uint64, tag = "2")]
    pub timestamp_nano: u64,
    #[prost(oneof = "profiling_data::Payload", tags = "3, 4, 5, 6")]
    pub payload: ::core::option::Option<profiling_data::Payload>,
}
/// Nested message and enum types in `ProfilingData`.
pub mod profiling_data {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum DataType {
        UnknownData = 0,
        CpuData = 1,
        MemoryData = 2,
        ThreadData = 3,
        Heartbeat = 4,
    }
    impl DataType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::UnknownData => "UNKNOWN_DATA",
                Self::CpuData => "CPU_DATA",
                Self::MemoryData => "MEMORY_DATA",
                Self::ThreadData => "THREAD_DATA",
                Self::Heartbeat => "HEARTBEAT",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNKNOWN_DATA" => Some(Self::UnknownData),
                "CPU_DATA" => Some(Self::CpuData),
                "MEMORY_DATA" => Some(Self::MemoryData),
                "THREAD_DATA" => Some(Self::ThreadData),
                "HEARTBEAT" => Some(Self::Heartbeat),
                _ => None,
            }
        }
    }
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "3")]
        CpuData(super::CpuData),
        #[prost(message, tag = "4")]
        MemoryData(super::MemoryData),
        #[prost(message, tag = "5")]
        ThreadData(super::ThreadData),
        #[prost(message, tag = "6")]
        Heartbeat(super::HeartbeatData),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CpuData {
    #[prost(uint64, tag = "1")]
    pub total_sample_count: u64,
    #[prost(uint32, tag = "2")]
    pub sampling_interval_ms: u32,
    #[prost(message, optional, tag = "3")]
    pub method_graph: ::core::option::Option<MethodGraph>,
    #[prost(message, optional, tag = "4")]
    pub call_tree: ::core::option::Option<CallTree>,
    #[prost(message, repeated, tag = "5")]
    pub hot_spots: ::prost::alloc::vec::Vec<HotSpot>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HotSpot {
    #[prost(string, tag = "1")]
    pub class_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub method_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub method_descriptor: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub self_samples: u64,
    #[prost(uint64, tag = "5")]
    pub total_samples: u64,
    #[prost(uint64, tag = "6")]
    pub self_duration_nano: u64,
    #[prost(uint64, tag = "7")]
    pub total_duration_nano: u64,
    #[prost(double, tag = "8")]
    pub percent: f64,
    #[prost(uint64, tag = "9")]
    pub invocations: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MethodGraph {
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<MethodNode>,
    #[prost(message, repeated, tag = "2")]
    pub edges: ::prost::alloc::vec::Vec<MethodEdge>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MethodNode {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub class_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub method_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub method_descriptor: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub execution_count: u64,
    #[prost(uint64, tag = "6")]
    pub total_duration_nano: u64,
    #[prost(uint64, tag = "7")]
    pub self_duration_nano: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MethodEdge {
    #[prost(int32, tag = "1")]
    pub from_node_id: i32,
    #[prost(int32, tag = "2")]
    pub to_node_id: i32,
    #[prost(uint64, tag = "3")]
    pub call_count: u64,
    #[prost(uint64, tag = "4")]
    pub total_duration_nano: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CallTree {
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<CallTreeNode>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CallTreeNode {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int32, tag = "2")]
    pub parent_id: i32,
    #[prost(string, tag = "3")]
    pub class_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub method_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub method_descriptor: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub file_name: ::prost::alloc::string::String,
    #[prost(int32, tag = "7")]
    pub line_number: i32,
    #[prost(uint64, tag = "8")]
    pub self_duration_nano: u64,
    #[prost(uint64, tag = "9")]
    pub total_duration_nano: u64,
    #[prost(uint64, tag = "10")]
    pub call_count: u64,
    #[prost(int32, repeated, tag = "11")]
    pub children: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemoryData {
    #[prost(message, optional, tag = "1")]
    pub allocation_tree: ::core::option::Option<AllocationTree>,
    #[prost(message, repeated, tag = "2")]
    pub heap_object_infos: ::prost::alloc::vec::Vec<HeapObjectInfo>,
    #[prost(uint64, tag = "3")]
    pub heap_used_bytes: u64,
    #[prost(uint64, tag = "4")]
    pub heap_committed_bytes: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AllocationTree {
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<AllocationTreeNode>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AllocationTreeNode {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int32, tag = "2")]
    pub parent_id: i32,
    #[prost(string, tag = "3")]
    pub class_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub method_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub method_descriptor: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub file_name: ::prost::alloc::string::String,
    #[prost(int32, tag = "7")]
    pub line_number: i32,
    #[prost(string, tag = "8")]
    pub allocated_type: ::prost::alloc::string::String,
    #[prost(uint64, tag = "9")]
    pub allocated_size: u64,
    #[prost(uint64, tag = "10")]
    pub instance_count: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HeapObjectInfo {
    #[prost(uint64, tag = "1")]
    pub object_id: u64,
    #[prost(string, tag = "2")]
    pub class_name: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub size: u64,
    #[prost(uint64, repeated, tag = "4")]
    pub references_to: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, repeated, tag = "5")]
    pub references_from: ::prost::alloc::vec::Vec<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ThreadData {
    #[prost(message, repeated, tag = "1")]
    pub thread_infos: ::prost::alloc::vec::Vec<ThreadInfo>,
    #[prost(uint64, tag = "2")]
    pub total_thread_count: u64,
    #[prost(uint64, tag = "3")]
    pub runnable_count: u64,
    #[prost(uint64, tag = "4")]
    pub waiting_count: u64,
    #[prost(uint64, tag = "5")]
    pub blocked_count: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ThreadInfo {
    #[prost(int64, tag = "1")]
    pub thread_id: i64,
    #[prost(string, tag = "2")]
    pub thread_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub thread_state: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub stack_trace: ::prost::alloc::vec::Vec<StackTraceElement>,
    #[prost(string, tag = "5")]
    pub lock_info: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StackTraceElement {
    #[prost(string, tag = "1")]
    pub class_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub method_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub file_name: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub line_number: i32,
    #[prost(bool, tag = "5")]
    pub native_method: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HeartbeatData {
    #[prost(uint64, tag = "1")]
    pub uptime_nano: u64,
    #[prost(uint32, tag = "2")]
    pub active_recordings: u32,
}
